/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;

/**
 *
 * @author TraderG
 */
public class LandingPage extends javax.swing.JFrame {

    /**
     * Creates new form LandingPage
     */
    public LandingPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        Title1 = new javax.swing.JLabel();
        Title2 = new javax.swing.JLabel();
        btnLearnMore = new javax.swing.JButton();
        Contacts = new javax.swing.JButton();
        Contacts1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnGetStarted = new javax.swing.JButton();
        Title4 = new javax.swing.JLabel();
        Title3 = new javax.swing.JLabel();
        Title6 = new javax.swing.JLabel();
        Title5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setUndecorated(true);

        BG.setBackground(new java.awt.Color(0, 55, 119));
        BG.setMaximumSize(new java.awt.Dimension(1200, 700));
        BG.setPreferredSize(new java.awt.Dimension(1200, 700));
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        BG.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 18, -1, -1));

        Title.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("BizPlatform");
        BG.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 18, 211, -1));

        Title1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Title1.setForeground(new java.awt.Color(255, 255, 255));
        Title1.setText("Project");
        BG.add(Title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 209, -1, -1));

        Title2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Title2.setForeground(new java.awt.Color(255, 255, 255));
        Title2.setText("Business Management");
        BG.add(Title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 263, 578, -1));

        btnLearnMore.setBackground(new java.awt.Color(37, 86, 134));
        btnLearnMore.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLearnMore.setForeground(new java.awt.Color(255, 255, 255));
        btnLearnMore.setText("LEARN MORE");
        btnLearnMore.setBorder(null);
        btnLearnMore.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BG.add(btnLearnMore, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 423, 140, 38));

        Contacts.setBackground(new java.awt.Color(35, 59, 126));
        Contacts.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Contacts.setForeground(new java.awt.Color(255, 255, 255));
        Contacts.setText("Contacts");
        Contacts.setBorder(null);
        Contacts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BG.add(Contacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(796, 27, 75, -1));

        Contacts1.setBackground(new java.awt.Color(35, 59, 126));
        Contacts1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Contacts1.setForeground(new java.awt.Color(255, 255, 255));
        Contacts1.setText("Services");
        Contacts1.setBorder(null);
        Contacts1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BG.add(Contacts1, new org.netbeans.lib.awtextra.AbsoluteConstraints(902, 27, 75, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\TraderG\\Downloads\\PROJECTS\\BizPlatform\\icons\\folder-management.png")); // NOI18N
        BG.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 125, -1, -1));

        btnGetStarted.setBackground(new java.awt.Color(37, 86, 134));
        btnGetStarted.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGetStarted.setForeground(new java.awt.Color(255, 255, 255));
        btnGetStarted.setText("GET STARTED");
        btnGetStarted.setBorder(null);
        btnGetStarted.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGetStarted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetStartedActionPerformed(evt);
            }
        });
        BG.add(btnGetStarted, new org.netbeans.lib.awtextra.AbsoluteConstraints(1007, 22, 140, 38));

        Title4.setForeground(new java.awt.Color(255, 255, 255));
        Title4.setText("business operations, including inventory, sales, customer relationship management (CRM) employee");
        BG.add(Title4, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 345, -1, -1));

        Title3.setForeground(new java.awt.Color(255, 255, 255));
        Title3.setText("BizPlatform is a comprehensive, desktop-based Business Management Platform designed to streamline core   ");
        BG.add(Title3, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 323, -1, -1));

        Title6.setForeground(new java.awt.Color(255, 255, 255));
        Title6.setText("management, financial tracking, and advanced analytics empowers small to medium-sized ");
        BG.add(Title6, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 367, -1, -1));

        Title5.setForeground(new java.awt.Color(255, 255, 255));
        Title5.setText(" improve operational efficiency. enterprises (SMEs) to optimize workflows");
        BG.add(Title5, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 389, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGetStartedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetStartedActionPerformed
        // TODO add your handling code here:
        // Create and show UserInterface
        UserInterface userInterface = new UserInterface();
        userInterface.setVisible(true);
    
        // Close the current LandingPage
        this.dispose();
    }//GEN-LAST:event_btnGetStartedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LandingPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JButton Contacts;
    private javax.swing.JButton Contacts1;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Title1;
    private javax.swing.JLabel Title2;
    private javax.swing.JLabel Title3;
    private javax.swing.JLabel Title4;
    private javax.swing.JLabel Title5;
    private javax.swing.JLabel Title6;
    private javax.swing.JButton btnGetStarted;
    private javax.swing.JButton btnLearnMore;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
